-- Add CRM columns to Leads table
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS PipelineId INTEGER REFERENCES Pipelines(Id);
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS StageId INTEGER REFERENCES PipelineStages(Id);
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS StageEnteredAt TIMESTAMP;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS Score INTEGER DEFAULT 0;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS LastScoreUpdate TIMESTAMP;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS OwnerId TEXT REFERENCES AspNetUsers(Id);
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS LeadSource TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS LeadSourceDetail TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS PageViews INTEGER DEFAULT 0;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS TotalVisits INTEGER DEFAULT 0;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS FirstVisitAt TIMESTAMP;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS LastVisitAt TIMESTAMP;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS AverageTimeOnSite INTEGER;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS EmailOpens INTEGER DEFAULT 0;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS EmailClicks INTEGER DEFAULT 0;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS Industry TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS JobTitle TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS City TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS State TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS Country TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS Website TEXT;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS EmployeeCount INTEGER;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS AnnualRevenue DECIMAL;

-- Add API & Tracking columns to Tenants table
ALTER TABLE Tenants ADD COLUMN IF NOT EXISTS ApiKey TEXT;
ALTER TABLE Tenants ADD COLUMN IF NOT EXISTS TrackingCode TEXT;

-- Create Pipelines table
CREATE TABLE IF NOT EXISTS Pipelines (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantId INTEGER NOT NULL REFERENCES Tenants(Id),
    Name TEXT NOT NULL,
    Description TEXT,
    IsDefault INTEGER DEFAULT 0,
    "Order" INTEGER DEFAULT 0,
    IsActive INTEGER DEFAULT 1,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create PipelineStages table
CREATE TABLE IF NOT EXISTS PipelineStages (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    PipelineId INTEGER NOT NULL REFERENCES Pipelines(Id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Description TEXT,
    Color TEXT DEFAULT '#667eea',
    "Order" INTEGER DEFAULT 0,
    IsActive INTEGER DEFAULT 1,
    IsWonStage INTEGER DEFAULT 0,
    IsLostStage INTEGER DEFAULT 0,
    ExpectedDaysInStage INTEGER,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create LeadActivities table
CREATE TABLE IF NOT EXISTS LeadActivities (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    LeadId INTEGER NOT NULL REFERENCES Leads(Id) ON DELETE CASCADE,
    TenantId INTEGER NOT NULL REFERENCES Tenants(Id),
    Type INTEGER NOT NULL,
    Title TEXT NOT NULL,
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PerformedByUserId TEXT REFERENCES AspNetUsers(Id),
    Metadata TEXT,
    PageUrl TEXT,
    PageTitle TEXT,
    TimeOnPage INTEGER,
    DeviceType TEXT,
    Browser TEXT,
    Location TEXT
);

-- Create LeadStageHistories table
CREATE TABLE IF NOT EXISTS LeadStageHistories (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    LeadId INTEGER NOT NULL REFERENCES Leads(Id) ON DELETE CASCADE,
    FromStageId INTEGER REFERENCES PipelineStages(Id),
    ToStageId INTEGER NOT NULL REFERENCES PipelineStages(Id),
    MovedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MovedByUserId TEXT REFERENCES AspNetUsers(Id),
    Notes TEXT,
    DaysInPreviousStage INTEGER DEFAULT 0
);

-- Create LeadScores table
CREATE TABLE IF NOT EXISTS LeadScores (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    LeadId INTEGER NOT NULL REFERENCES Leads(Id) ON DELETE CASCADE,
    Score INTEGER DEFAULT 0,
    Reason TEXT,
    CalculatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create LeadTags table
CREATE TABLE IF NOT EXISTS LeadTags (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantId INTEGER NOT NULL REFERENCES Tenants(Id),
    Name TEXT NOT NULL,
    Color TEXT DEFAULT '#667eea',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create LeadTagMapping table (many-to-many)
CREATE TABLE IF NOT EXISTS LeadLeadTag (
    LeadsId INTEGER NOT NULL REFERENCES Leads(Id) ON DELETE CASCADE,
    TagsId INTEGER NOT NULL REFERENCES LeadTags(Id) ON DELETE CASCADE,
    PRIMARY KEY (LeadsId, TagsId)
);

-- Create LeadCustomFields table
CREATE TABLE IF NOT EXISTS LeadCustomFields (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantId INTEGER NOT NULL REFERENCES Tenants(Id),
    FieldName TEXT NOT NULL,
    FieldLabel TEXT NOT NULL,
    FieldType INTEGER NOT NULL,
    DefaultValue TEXT,
    IsRequired INTEGER DEFAULT 0,
    IsActive INTEGER DEFAULT 1,
    "Order" INTEGER DEFAULT 0,
    Options TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create CrmTasks table
CREATE TABLE IF NOT EXISTS CrmTasks (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantId INTEGER NOT NULL REFERENCES Tenants(Id),
    LeadId INTEGER REFERENCES Leads(Id) ON DELETE SET NULL,
    Title TEXT NOT NULL,
    Description TEXT,
    DueDate TIMESTAMP,
    Priority INTEGER DEFAULT 1,
    Status INTEGER DEFAULT 0,
    AssignedToUserId TEXT REFERENCES AspNetUsers(Id),
    CreatedByUserId TEXT NOT NULL REFERENCES AspNetUsers(Id),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CompletedAt TIMESTAMP
);

-- Create Deals table
CREATE TABLE IF NOT EXISTS Deals (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantId INTEGER NOT NULL REFERENCES Tenants(Id),
    LeadId INTEGER NOT NULL REFERENCES Leads(Id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Amount DECIMAL NOT NULL,
    Currency TEXT DEFAULT 'USD',
    Probability DECIMAL DEFAULT 50,
    ExpectedCloseDate TIMESTAMP,
    ActualCloseDate TIMESTAMP,
    Status INTEGER DEFAULT 0,
    Notes TEXT,
    OwnerId TEXT REFERENCES AspNetUsers(Id),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IX_LeadActivities_LeadId ON LeadActivities(LeadId);
CREATE INDEX IF NOT EXISTS IX_LeadActivities_TenantId ON LeadActivities(TenantId);
CREATE INDEX IF NOT EXISTS IX_Pipelines_TenantId ON Pipelines(TenantId);
CREATE INDEX IF NOT EXISTS IX_PipelineStages_PipelineId ON PipelineStages(PipelineId);
CREATE INDEX IF NOT EXISTS IX_LeadStageHistories_LeadId ON LeadStageHistories(LeadId);
CREATE INDEX IF NOT EXISTS IX_LeadScores_LeadId ON LeadScores(LeadId);
CREATE INDEX IF NOT EXISTS IX_LeadTags_TenantId ON LeadTags(TenantId);
CREATE INDEX IF NOT EXISTS IX_CrmTasks_LeadId ON CrmTasks(LeadId);
CREATE INDEX IF NOT EXISTS IX_CrmTasks_TenantId ON CrmTasks(TenantId);
CREATE INDEX IF NOT EXISTS IX_Deals_LeadId ON Deals(LeadId);
CREATE INDEX IF NOT EXISTS IX_Deals_TenantId ON Deals(TenantId);
CREATE INDEX IF NOT EXISTS IX_Leads_PipelineId ON Leads(PipelineId);
CREATE INDEX IF NOT EXISTS IX_Leads_StageId ON Leads(StageId);
CREATE INDEX IF NOT EXISTS IX_Leads_OwnerId ON Leads(OwnerId);
